Adding info to knowledge guide
instructlab/community pull request #161
Opened 2024-04-16 17:40 UTC by kelbrown20

**Description:** Adding more info to knowledge-guide fix

Fixing some descriptions still

2024-04-16 18:00 UTC, jjasghar approved these changes

2024-04-16 20:14 UTC, bjhargrave requested changes
Some comments

2024-04-17 08:34 UTC, lhawthorn requested changes
Minor nit feedback, but please address it.

Seconding @jjasghar's "oh my goodness this is exactly what we need"

Thank you so much for this contribution!

2024-04-17 15:40 UTC, oindrillac reviewed
This is great! I think we also need a brief section on the content of the document, and what types of documents are good contributions vs not. For example https://github.com/juliadenham/oscars2024_knowledge/blob/main/oscars2024_results.md wiki doc was hard for the model to read because of the implicit assumptions made by formatting which are easy for humans to read but not for models and therefore that PR did not make it to the model release.
@kelbrown20 let me know if you need help elaborating on that.

EDIT: Maybe taxonomy docs is a better location for that kind of documentation, realized that this is community guidelines focused. Either way, happy to help!

2024-04-18 16:50 UTC, bjhargrave requested changes

2024-04-18 19:40 UTC, merged