Add spellcheck workflow
instructlab/community pull request #162
Opened 2024-04-16 17:57 UTC by jjasghar

We have a bunch of documentation, it wouldn't hurt to have spell check.

2024-04-16 20:17 UTC, bjhargrave requested changes
I think you also need to include the configuration files.
<img width="869" alt="Screenshot 2024-04-16 at 16 17 00" src="https://github.com/instruct-lab/community/assets/277682/1db33982-2113-45bb-938d-4c0eb62f935b">

2024-04-19 19:38 UTC, lhawthorn approved these changes
LGTM

2024-04-24 14:22 UTC, bjhargrave requested changes
Looking at the gha action, it requires a spellcheck.yml file which is not included in this PR.

For example: https://github.com/instructlab/instructlab/blob/main/.spellcheck.yml

I tested this PR in my fork and the spell check failed due to missing spellcheck.yml file.

```
Using pyspelling on configuration outlined in >spellcheck.yaml<
Checking files matching specified outlined in >spellcheck.yaml<
----------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/pyspelling", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyspelling/__main__.py", line 30, in main
    return run(
           ^^^^
  File "/usr/local/lib/python3.12/site-packages/pyspelling/__main__.py", line 55, in run
    for results in spellcheck(
  File "/usr/local/lib/python3.12/site-packages/pyspelling/__init__.py", line 616, in spellcheck
    config = util.read_config(config_file)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyspelling/util/__init__.py", line 186, in read_config
    raise ValueError(
ValueError: Unable to find or load pyspelling configuration from spellcheck.yaml, for more details on configuration please read https://facelessuser.github.io/pyspelling/configuration/
```

2024-04-25 03:15 UTC, ckadner requested changes, later dismissed
Nice!

2024-04-25 03:15 UTC, ckadner commented on .github/workflows/spellcheck.yaml
> +      - '**.md'
```suggestion
      - .github/workflows/spellcheck.yaml
      - '**.md'
```

2024-04-25 15:40 UTC, nathan-weinberg commented
Very much in favor of this

2024-04-25 17:46 UTC, ckadner commented
> > It doesn't seem to unless we want to add a specific dictionary.
> > https://github.com/marketplace/actions/github-spellcheck-action#configuration
> 
> Step 2 says you need to create a `spellcheck.yml` file.

https://github.com/instructlab/community/actions/runs/8835495973/job/24259773634?pr=162#step:4:19

```
  File "/usr/local/lib/python3.12/site-packages/pyspelling/__init__.py", line 616, in spellcheck
    config = util.read_config(config_file)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyspelling/util/__init__.py", line 186, in read_config
    raise ValueError(
ValueError: Unable to find or load pyspelling configuration from spellcheck.yaml, for more details on configuration please read https://facelessuser.github.io/pyspelling/configuration/
Error: Files in repository contain spelling errors
```

2024-04-25 18:01 UTC, bjhargrave commented
Also, this PR needs to fix any spelling errors that may exist so that the repo passes the spellcheck action.

2024-04-26 18:08 UTC, nathan-weinberg commented
> Ok, I've got to say it: I don't know why everybody seems to love those spellcheckers. In my experience they are a pain because there generate too many false positives. We're not producing literature and there are just too many terms we use that spellcheckers don't know, and about every PR needs to include its additions to the custom dictionary. Now, feel free to ignore me, I've said my piece.

I think it makes a lot of sense given the doc-heavy nature of this repo, and I don't think the dictionary maintenence is going to be too hard once we get a lot of the base terms out of the way.

I've opened a PR for a Markdown Linter for this repo as well, they should pair well together: https://github.com/instructlab/community/pull/218

2024-05-03 16:24 UTC, bjhargrave approved these changes

2024-05-03 17:17 UTC, nathan-weinberg approved these changes

2024-05-03 17:18 UTC, nathan-weinberg commented
@ckadner can you take another look and approve/merge if things look good to you?

2024-05-03 18:30 UTC, merged