Docs: Add refrences to granite model to community docs
instructlab/community pull request #232
Opened 2024-05-02 00:33 UTC by kelbrown20

**Description:** Adding info and references to the granite model to the community repo

Getting some more details on granite, so this is not up to date

2024-05-02 07:38 UTC, lhawthorn requested changes
Looks good to me so far. Would appreciate review of my comments and either updates or helping with my understanding. Will not merge until you give me the thumbs up, too, as the original PR indicates not complete.

2024-05-02 14:51 UTC, JamesKunstle commented on FAQ.md
>  When contributors write an extension to the existing taxonomy, make a pull request, and get it reviewed and merged, their changes are rolled out in the next build. This update strategy expedites the
r/extension/addition

2024-05-02 14:52 UTC, JamesKunstle commented on FAQ.md
> +Contributions to the InstructLab project update Merlinite-7b or Granite-7b, an open source licensed LLM. Contributors have direct access to the model they are improving through [Hugging Face](https:/
r/update/fine-tune

2024-05-02 14:52 UTC, JamesKunstle commented on FAQ.md
> +Granite-7b is a model that was build from scratch and fine tuned with the LAB (**L**arge-scale **A**lignment for chat**B**ots) process  .
r/build/built, `from scratch by IBM`

2024-05-02 14:54 UTC, JamesKunstle commented on FAQ.md
> +The InstructLab project and the Merlinite-7b & Granite-7b models are distributed under [Apache License, Version 2.0](https://www.apache.org/licenses/LICENSE-2.0).
"The InstructLab project and the Merlinite-7b and Granite-7b models"

2024-05-02 14:55 UTC, JamesKunstle requested changes
Read through the changes, made a few requests for changes in form / specificity.

2024-05-02 17:58 UTC, kelbrown20 commented on FAQ.md
> +InstructLab is designed to enable collaboration around Merlinite-7b and Granite-7b, an open source licensed LLM that contributors can access through [Hugging Face](https://huggingface.co/collections/
Yes I agree with that, I'll update this link

2024-05-02 18:19 UTC, kelbrown20 commented
@lhawthorn Can you PTAL when you get the chance?

2024-05-03 18:39 UTC, lhawthorn approved these changes
LGTM

2024-05-03 18:41 UTC, bjhargrave commented
@kelbrown20 Can you rebase on main? There is a new action to spell check.

2024-05-04 04:14 UTC, nathan-weinberg commented on FAQ.md
> +  - [What is Granite-7b-lab](#what-is-granite-7-lab)
```suggestion
  - [What is Granite-7b-lab?](#what-is-granite-7-lab)
```

2024-05-04 04:14 UTC, nathan-weinberg commented on FAQ.md
> +More information about the LAB method can be found on this [Hugging Face project page](https://huggingface.co/instructlab).
```suggestion
More information about the LAB method can be found on the [Hugging Face project page](https://huggingface.co/instructlab).
```

2024-05-04 04:14 UTC, nathan-weinberg commented on FAQ.md
> +Merlinite-7b is a Mistral-7b derivative model fine tuned with the LAB (**L**arge-scale **A**lignment for chat**B**ots) process using Mixtral-8x7b-Instruct as a teacher model.
```suggestion
Merlinite-7b is a Mistral-7b derivative model fine tuned with the LAB (**L**arge-scale **A**lignment for chat**B**ots) method using Mixtral-8x7b-Instruct as a teacher model.
```

2024-05-04 04:14 UTC, nathan-weinberg commented on FAQ.md
> +Granite-7b-lab is a model that was built from scratch by IBM and fine tuned with the LAB (**L**arge-scale **A**lignment for chat**B**ots) process.
```suggestion
Granite-7b-lab is a model that was built from scratch by IBM and fine tuned with the LAB (**L**arge-scale **A**lignment for chat**B**ots) method.
```

2024-05-04 04:14 UTC, nathan-weinberg commented on FAQ.md
> +The InstructLab project and the Merlinite-7b and Granite-7b models are distributed under [Apache License, Version 2.0](https://www.apache.org/licenses/LICENSE-2.0).
```suggestion
The InstructLab project as well as the Merlinite-7b and Granite-7b models are distributed under [Apache License, Version 2.0](https://www.apache.org/licenses/LICENSE-2.0).
```

2024-05-04 04:14 UTC, nathan-weinberg commented on README.md
> +The models Merlinite-7b and Granite-7b builds regularly. Sometime after your pull request is merged, Merlinite is updated and you can see locally that the model improved with the skill or knowledge y
```suggestion
The Merlinite-7b and Granite-7b models are built regularly. Sometime after your pull request is merged, Merlinite is updated and you can see locally that the model improved with the skill or knowledge you taught it.
```

2024-05-04 15:11 UTC, kelbrown20 commented on README.md
> +The models Merlinite-7b and Granite-7b builds regularly. Sometime after your pull request is merged, Merlinite is updated and you can see locally that the model improved with the skill or knowledge y
I usually prefer active voice when I can, but lemme see if I can re word something

2024-05-04 18:00 UTC, nathan-weinberg commented on README.md
> +The models Merlinite-7b and Granite-7b builds regularly. Sometime after your pull request is merged, Merlinite is updated and you can see locally that the model improved with the skill or knowledge y
Honestly just an idea from me - I trust your judgement!

2024-05-06 17:24 UTC, merged