update installation
instructlab/community pull request #251
Opened 2024-05-12 23:35 UTC by celek

https://github.com/instructlab/instructlab/ has a newer getting started

2024-05-12 23:54 UTC, russellb commented
Maybe we should just remove this file completely and replace all references to the `instructlab/instructlab` README ?

2024-05-12 23:57 UTC, celek commented
> Maybe we should just remove this file completely and replace all references to the `instructlab/instructlab` README ?

i am ok with that - at least , as a new user, I can test that my `ilab generate` and `ilab train` work ? 
Should we then 
- explain how to create a PR 
- explain how remove that PR (so not all new user submit the same PR) ?

2024-05-13 12:43 UTC, bjhargrave requested changes
I think we need to separate the doc for installing ilab and making sure it is setup for acceleration from a complete, worked example. The quick start should only discuss the basics of installing ilab and link to more complete docs and then move on to complete the example. 

Some have found the complete example in the quick start helpful so I would not remove it or fold it into the main readme.

cc @jjasghar

2024-05-13 12:43 UTC, bjhargrave commented on QUICK_START_GUIDE.md
> +       -C cmake.args="-DCMAKE_PREFIX_PATH=/opt/rocm"
```suggestion
   (venv) $ pip install git+https://github.com/instructlab/instructlab.git@stable \
       --extra-index-url https://download.pytorch.org/whl/rocm6.0 \
       -C cmake.args="-DLLAMA_HIPBLAS=on;-DAMDGPU_TARGETS=all;-DCMAKE_C_COMPILER=/opt/rocm/llvm/bin/clang;-DCMAKE_CXX_COMPILER=/opt/rocm/llvm/bin/clang++;-DCMAKE_PREFIX_PATH=/opt/rocm"
```

You can combine the cmake args with `;` separators.

2024-05-13 12:43 UTC, bjhargrave commented on QUICK_START_GUIDE.md
> +   (venv) $ pip install git+https://github.com/instructlab/instructlab.git@stable -C cmake.args="-DLLAMA_METAL=on"
```suggestion
   (venv) $ pip install git+https://github.com/instructlab/instructlab.git@stable -C cmake.args="-DLLAMA_METAL=on;-DCMAKE_OSX_ARCHITECTURES=arm64;-DCMAKE_APPLE_SILICON_PROCESSOR=arm64"
```

Some users end up compiling for x86_64. Adding these arm64 flags avoids this.

2024-05-13 15:48 UTC, jjasghar requested changes
Made a few comments.

I think the challenge was that this was designed for Workshops/Labs quick start guide and you're trying to turn it into a full start guide.

I think we should keep many of your changes in the main README.md and maybe pull this full setup into the main "docs site" that we are going to build eventually.

/cc @kelbrown20 @juliadenham

2024-05-13 15:48 UTC, jjasghar commented on QUICK_START_GUIDE.md
> -## 📋 Requirements
If you are just receiving this document, you should see this first to see if you can even run this on your laptop.

2024-05-13 15:48 UTC, jjasghar commented on QUICK_START_GUIDE.md
> +   ```shell
These are bash commands. why `shell`? there's no difference.

2024-05-13 15:48 UTC, jjasghar commented on QUICK_START_GUIDE.md
> +   See [the GPU acceleration documentation](./docs/gpu-acceleration.md) for how to
We didn't want to "link off this page." The idea is that this is the "no fluff" way to get `ilab` working, for labs or workshops and the like. This stuff is for the main README in `instructlab/instructlab`

2024-05-13 15:48 UTC, jjasghar commented on QUICK_START_GUIDE.md
> +   --version      Show the version and exit.
Ah yep, good catch, the `cli` has been updated since.

2024-05-13 15:48 UTC, jjasghar commented on QUICK_START_GUIDE.md
> +5. You may optionally enable tab completion for the `ilab` command.
I strongly suggest not having this in this document. Adding this to a lab/workshop document will only confuse students.

2024-05-13 15:48 UTC, jjasghar commented on QUICK_START_GUIDE.md
> +   Cloning https://github.com/instructlab/taxonomy.git...
I believe this still hasn't been updated? Or if it has I haven't seen the PR.

2024-07-15 22:09 UTC, nathan-weinberg commented
@celek do you intend to revisit this PR?

2024-07-16 01:34 UTC, closed without merging