COCC should be named something different.
instructlab/community pull request #280
Opened 2024-05-20 21:56 UTC by jjasghar

COCC should be named CODE_OF_CONDUCT_COMMITEE.

2024-05-20 22:12 UTC, bjhargrave requested changes
You need to change all the places which refer to this name. 

https://github.com/search?q=org%3Ainstructlab%20COCC.md&type=code

Last file name change broke many references.

2024-05-21 01:26 UTC, russellb commented
good catch ...

2024-05-29 12:57 UTC, bjhargrave commented
@mergifyio rebase

2024-05-29 13:01 UTC, bjhargrave approved these changes

2024-05-29 13:03 UTC, merged