Update FAQ.md
instructlab/community pull request #282
Opened 2024-05-20 22:13 UTC by jjasghar

Updated the correct location for some documents, and removed some `-`.

2024-05-20 22:17 UTC, bjhargrave requested changes

2024-05-20 22:17 UTC, bjhargrave commented on FAQ.md
> +- [**Composition skills.**](https://github.com/instructlab/community/blob/main/docs/SKILLS_GUIDE.md#compositional-skills) Composition or _performative_ skills allow AI models to perform specific task
I think these linked files are now in the taxonomy repo.

```suggestion
- [**Composition skills.**](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#compositional-skills) Composition or _performative_ skills allow AI models to perform specific tasks or functions. With InstructLab, there are two types of composition skills:
```

2024-05-20 22:17 UTC, bjhargrave commented on FAQ.md
> +  - [**Freeform compositional skills**](https://github.com/instructlab/community/blob/main/docs/SKILLS_GUIDE.md#freeform-compositional-skills) are performative skills that do not require additional c
```suggestion
  - [**Freeform compositional skills**](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#freeform-compositional-skills) are performative skills that do not require additional context. For example, to train an AI model to write a poem, you would provide examples of poems.
```

2024-05-20 22:17 UTC, bjhargrave commented on FAQ.md
> +  - [**Grounded compositional skills**](https://github.com/instructlab/community/blob/main/docs/SKILLS_GUIDE.md#grounded-compositional-skills) are performative skills that require additional context.
```suggestion
  - [**Grounded compositional skills**](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#grounded-compositional-skills) are performative skills that require additional context. One example is how an AI model reads the value of a cell in a table layout. To create the grounded skill to read a table formatted in Markdown, the additional context might be an example table layout.
```

2024-05-21 11:59 UTC, lhawthorn approved these changes

2024-05-21 12:00 UTC, lhawthorn commented
@jjasghar Please rebase so I can do a final review, but what I have reviewed thus far LGTM.

2024-05-21 12:07 UTC, bjhargrave commented
@mergifyio rebase

2024-05-21 12:08 UTC, bjhargrave approved these changes

2024-05-22 12:42 UTC, kelbrown20 approved these changes

2024-05-22 12:45 UTC, merged