Update docs to explain how MAINTAINERS file is managed
instructlab/community pull request #348
Opened 2024-08-08 19:43 UTC by booxter

It's no longer manually edited by maintainers. Instead, a new member is added to the appropriate GitHub group, and then a periodic bot posts a PR to update the file.

---

I **think** this is correct, but someone with better knowledge of how this works should confirm - I never added or removed anyone myself.

2024-09-03 16:51 UTC, nathan-weinberg approved these changes

2024-09-03 16:56 UTC, bjhargrave requested changes

2024-09-03 16:56 UTC, bjhargrave commented on CONTRIBUTOR_ROLES.md
> +After a [decision has been made](https://github.com/instructlab/community/blob/main/governance.md#decision-making-at-the-instructlab-org-level), a Maintainer will add you to the appropriate group wit
```suggestion
After a [decision has been made](https://github.com/instructlab/community/blob/main/governance.md#decision-making-at-the-instructlab-org-level), a Maintainer will add you to the appropriate group within three weeks. A [workflow](https://github.com/instructlab/community/blob/main/.github/workflows/periodic-maintainers-update.yml) runs daily and will submit a PR to update the [MAINTAINERS file](https://github.com/instructlab/community/blob/main/MAINTAINERS.md) to reflect the membership.
```

2024-09-04 15:34 UTC, bjhargrave approved these changes

2024-09-04 15:34 UTC, merged